/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.me.mutifuncalendar;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int arrow_left=0x7f020000;
        public static final int arrow_left_first=0x7f020001;
        public static final int arrow_left_last=0x7f020002;
        public static final int arrow_right=0x7f020003;
        public static final int arrow_right_first=0x7f020004;
        public static final int arrow_right_last=0x7f020005;
        public static final int background=0x7f020006;
    }
    public static final class id {
        public static final int backbutton=0x7f060003;
        public static final int dateId=0x7f060001;
        public static final int keypad=0x7f060000;
        public static final int menu_back_now_id=0x7f060005;
        public static final int menu_note_id=0x7f060004;
        public static final int scanbutton=0x7f060002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int monthview=0x7f030001;
    }
    public static final class menu {
        public static final int monthmenu=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int menu_back_now=0x7f040001;
        public static final int menu_note=0x7f040002;
    }
}
